### ISSUE TITLE
Update developing for pipx docs to include pyproject.toml

### ISSUE THREAD

**Issue by Gitznik** [pypa/pipx#1229]
**How would this feature be useful?**

We currently only describe how to develop for pipx using `setup.py`. We should also describe how to do it via a `pyproject.toml`.

Based on a discussion in #1212 

**Describe the solution you'd like**

New section under https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx describing this.

**Describe alternatives you've considered**

None

**Comment by Gitznik** [comment]
Hi @IanHopkinson, thanks for doing the research!

We need to provide a way to support man pages via `pyproject.toml`. If that's possible without using the discouraged `data-files`, that's great. If not - I do think we need to include it in our docs.

**Comment by IanHopkinson** [comment]
No problem - my most popular blog post by an order of magnitude is on `pyproject.toml`!

As far as I can tell `data-files` is the only way to provide support for man pages. I'm assuming you want this so that tools installed by `pipx` look like first class citizens on UNIX-like systems. I think it is worth documenting that, since we are directing developers towards a "discouraged" feature. Here's an example of `data-files` in `pyproject.toml` used in the wild: https://setuptools-generate.readthedocs.io/en/latest/

As a Windows/git-bash user this man page functionality "Doesn't Work For Me (tm)!" since git-bash doesn't include man :-)

I can raise a PR documenting this if you like - I'll rely on the GitHub Actions to run testing since this is just a documentation change and shouldn't break any tests.

**Comment by Gitznik** [comment]
> I'm assuming you want this so that tools installed by `pipx` look like first class citizens on UNIX-like systems. I think it is worth documenting that, since we are directing developers towards a "discouraged" feature.

That's it. Feel free to include a note that states that using `data-files` is discouraged, but necessary for man files.

> I can raise a PR documenting this if you like - I'll rely on the GitHub Actions to run testing since this is just a documentation change and shouldn't break any tests.

Sounds great, thank you :)

**Comment by IanHopkinson** [comment]
PR submitted as suggested (#1274). Pre-commit failed initially on line endings since I am working on Windows, but it fixed this automatically. 

This is my largest open source contribution to date - my first was a single character (http->https), and my second a whole URL!

**Comment by Gitznik** [comment]
> This is my largest open source contribution to date - my first was a single character (http->https), and my second a whole URL!

Glad you decided to do it here :)

**Comment by IanHopkinson** [comment]
Things have escalated! I have installed build system so I can check the docs render correctly. Also I'm looking at the start of the "How it works" section and thinking it would be nice to describe what happens on Windows machines...

**Comment by Gitznik** [comment]
You're more than welcome to create issues and PRs for any other parts of the docs you think could need an update/extension  :+1:
