### ISSUE TITLE
Add @huxuan as maintainer

### ISSUE THREAD

**Issue by dukecat0** [pypa/pipx#1385]
Hi everyone,

As @huxuan has contributed a lot of PRs and has access to the Windows + WSL system, he can help us to handle Windows and other issues in this project, so I would like to invite him to be a maintainer.

cc @pypa/pipx-committers

**Comment by uranusjr** [comment]
Sounds good to me

**Comment by henryiii** [comment]
+1

**Comment by pfmoore** [comment]
@gaborbernat Is this not something the pipx team can do themselves? I'd expect the pipx admins to be able to do this (I'm not a maintainer on pipx, much less an admin). If the team can't do this themselves, I'd rather work out why and fix *that*, rather than having you rely on me to add new maintainers.

**Comment by gaborbernat** [comment]
> @gaborbernat Is this not something the pipx team can do themselves? I'd expect the pipx admins to be able to do this (I'm not a maintainer on pipx, much less an admin). If the team can't do this themselves, I'd rather work out why and fix _that_, rather than having you rely on me to add new maintainers.

I try to do this, but seemed that I can only add collaborators who are already member of the organization. There are definitely some permissions missing for us to do this.

**Comment by pfmoore** [comment]
OK, can we find out what's missing? I'm reluctant to lose the opportunity to work out how to properly fix this while we have a test case to hand (IIRC, I added a previous maintainer here, so this has been a problem for some time and it should get fixed properly - relying on me isn't sustainable in the long run).

**Comment by chrysle** [comment]
According to [this](https://docs.github.com/en/organizations/organizing-members-into-teams/adding-organization-members-to-a-team) and [this](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization), someone should be granted the admin role for this repository. @cs01 should already be an admin and be able to do that.

**Comment by pfmoore** [comment]
From what I can see, all pipx committers have the admin role:

![image](https://github.com/pypa/pipx/assets/1110419/fcc9564c-52d8-436c-a089-ed7be6736b1c)

There are 8 people in that team, including @gaborbernat and yourself:

![image](https://github.com/pypa/pipx/assets/1110419/9fd14ec6-fa0b-4c54-9d54-4f00fe7261ec)

I don't see why that doesn't give you the right to manage the project directly 🙁

**Comment by dukecat0** [comment]
I think before we can add someone to the team, they need to be invited to join the pypa organization first.

<img width="790" alt="image" src="https://github.com/pypa/pipx/assets/68463158/2b921de8-343e-4e8e-9568-5246810425d6">

**Comment by chrysle** [comment]
> I think before we can add someone to the team, they need to be invited to join the pypa organization first.

Hmm, how did you get to this page?

**Comment by dukecat0** [comment]
https://github.com/orgs/pypa/teams/pipx-team, though this one isn't for the commit access.

**Comment by pfmoore** [comment]
That rings a bell. You can invite someone to the pypa org from https://github.com/orgs/pypa/people - can anyone here do that, or does it need some special privilege that we need to sort out?

**Comment by chrysle** [comment]
I think [only organization owners](https://docs.github.com/en/organizations/managing-membership-in-your-organization/inviting-users-to-join-your-organization) can do that.

**Comment by pfmoore** [comment]
Hmm, that seems limiting:

![image](https://github.com/pypa/pipx/assets/1110419/aa64ad08-b649-4d8b-b035-eb646a4b520a)

**Comment by pfmoore** [comment]
I'll ask the pypa owners what we should do about this - needing an organisation owner to invite anyone who needs to become a maintainer on any PyPA project doesn't really seem to fit with our policy of projects being self-governing. And if it is necessary, we should have a better way for projects to request an owner send out the invite, rather than trying to find individuals who might be able to help...

Also, I'll be honest, I don't know the implications of inviting someone to be a member of the PyPA github org. Given the recent xz issue, I'm not comfortable with the risk of accidentally giving people too much access, simply because of how we've structured the organisation.

Give me a while to check with people, but I can send an invite to @huxuan once we've worked out the policy implications...

**Comment by pfmoore** [comment]
OK, we've discussed this and pinging the admins to get an invite sent seems fine - no need for any additional bureaucracy.

I've sent an invite to @huxuan. And for future issues like this, we now have a @pypa/owners group that will ping all of the PyPA admins.

**Comment by huxuan** [comment]
Thanks everyone for the recognition. Wish more cooperation with you guys and more contribution to pipx, PyPA and Python community.

**Comment by chrysle** [comment]
Looks like there is nothing else to do here.

**Comment by dukecat0** [comment]
I think he still needs to be added to @pypa/pipx-committers.

**Comment by chrysle** [comment]
@dukecat0 Could you do that?

**Comment by huxuan** [comment]
I just found I can request to join and @uranusjr approved that very quickly. So we are done. Thanks again!
