### ISSUE TITLE
Support running & installing scripts with dependencies specified in __requires__

### ISSUE THREAD

**Issue by jwodder** [pypa/pipx#562]
So pipx can run scripts specified as URLs on the command line, but it seems that they're always run in the system Python environment, with no isolation or installation of any dependencies.  What would be useful would be if the script's dependencies were read from `__requires__` à la [pip-run](https://github.com/jaraco/pip-run) and then the script was run in an isolated environment with those dependencies installed.  It'd be even more useful if pipx could then permanently install a script with its dependencies, instead of keeping them around only for one run.

This would enable highly lightweight "packaging" of scripts.  Instead of having to fill out a `setup.py` or `pyproject.toml` and going through all that, authors would be able to distribute single-file programs by just specifying the dependencies in `__requires__` and telling their users to install with pipx.

**Comment by cs01** [comment]
This is a pretty cool idea. Is `__requires__` a standard or is it just something pip-run made up? I took a look at [`pip-run`'s code](https://github.com/jaraco/pip-run/blob/5ab91934bcdbe1181d2b08368cb9aa5c53a6ef69/pip_run/scripts.py#L71) and it wouldn't be too hard to adapt to pipx.

I was toying around with another project called [importation](https://github.com/cs01/importation) that does runtime dependency installation like [deno](https://deno.land/), but instead of searching out special variables like `__requires__` it monkeypatches the import system itself. It still needs more work though.

Regarding pipx running the script not in a virtual environment, that should probably be reconsidered regardless.

**Comment by jwodder** [comment]
`__requires__` is not a standard.  [It originated in setuptools](https://setuptools.readthedocs.io/en/latest/pkg_resources.html?highlight=__requires__#workingset-objects), and then one of the setuptools developers combined the idea with support for pip to create pip-run.

**Comment by gaborbernat** [comment]
> `__requires__` is not a standard. [It originated in setuptools](https://setuptools.readthedocs.io/en/latest/pkg_resources.html?highlight=__requires__#workingset-objects), and then one of the setuptools developers combined the idea with support for pip to create pip-run.

**Comment by Flimm** [comment]
`__requires__` is not a standard, but inline script metadata is, and pipx supports it. See [this section of pipx's documentation](https://pipx.pypa.io/stable/examples/#pipx-run-examples):

> If you have a script test.py that needs 3rd party libraries, you can add [inline script metadata](https://packaging.python.org/en/latest/specifications/inline-script-metadata/) in the style of PEP 723.
> 
> # test.py
> 
> ```
> # /// script
> # dependencies = ["requests"]
> # ///
> 
> import sys
> import requests
> project = sys.argv[1]
> pipx_data = requests.get(f"https://pypi.org/pypi/{project}/json").json()
> print(pipx_data["info"]["version"])
> ```
> 
> Then you can run it as follows:
> 
> > pipx run test.py pipx
> 1.1.0
>
