### ISSUE TITLE
Why is not pipx hosted under pypa github org?

### ISSUE THREAD

**Issue by ssbarnea** [pypa/pipx#596]
`pipx` is great and I cannot refrain from wondering why is not hosted under the same organization that hosts most python tools around packaging and distribution?

I would personally think that both pipx and pip itself would benefit from it as I see them complementing each other.

**Comment by gaborbernat** [comment]
Joining the PyPa is entirely up to the maintainers of the project, and subject to the approval of other PyPa maintainers per https://www.python.org/dev/peps/pep-0609/#addition-of-a-project-to-the-pypa.

I think the past and current active maintainers never bothered to initiate this project. I'm personally (as one of these) are +0.1 on this. Generally, the main benefit of joining PyPa is exposure, but this project is already popular on its own. Other benefits would be that active maintainers can vote in PyPa topics, but generally, this is just other projects joining the PyPa.

**Comment by gaborbernat** [comment]
The PyPA vote now went through, so this will happen once @cs01 or @itsayellow initiates the transfer. Note we should merge https://github.com/pipxproject/pipx/pull/692 before that.

**Comment by ssbarnea** [comment]
@gaborbernat I am really happy to hear that. I guess this opens the door for other pip-related tools to follow in the future? Some of them are extremely useful, like https://github.com/jazzband/pip-tools

IMHO by bringing pip-related tool developers closer to pypa folks, we are bringing a historical gap. That could make cross project collaboration more likely.

**Comment by uranusjr** [comment]
> I guess this opens the door for other pip-related tools to follow in the future?

The door has been open for quite a while actually. Current procedure is documented in [PEP 609](https://www.python.org/dev/peps/pep-0609/), but that PEP is merely documenting existing understandings so things date back more than that. But as mentioned above, it is up to individual project maintainers to initiate the process, so it’s up to pip-tools maintainers for pip-tools to move the repository. I’d imagine their situation is more complicated than pipx though, since Jazzband has a more diverse and different scope from PyPA, so pip-tools joining the PyPA may imply them leaving Jazzband.

**Comment by itsayellow** [comment]
Since we're now a project of PyPA I think we can close this issue now. 😄
