### ISSUE TITLE
Portable Xcopy-able Venvs

### ISSUE THREAD

**Issue by aaronsteers** [pypa/pipx#628]
**How would this feature be useful?**

- Ability to attach docker volumes (dir paths) directly to a running or "stock" docker image.
- Ability to archive, ship, and reuse/restore virtual environment directories across environments.
- Ability to dynamically compose complex environments from static/precompiled pipx package archives.

**Describe the solution you'd like**

If don't know if there would be technical blockers for this, but the idea would be:

On `Machine A`:

```bash
pipx install my-tool
pipx export my-tool ./my-tool.tar.gz
```

On `Machine B`:

```bash
pipx import ./my-tool.tar.gz
```

And similarly, when attached to a docker container:

```bash
myhost$ unzip ./my-tool.tar.gz ./my-tool
myhost$ docker run --it -v ./my-tool:/pipx/portable/my-tool pipx:py3.8
docker$ pipx load-from /pipx/portable
docker$ my-tool --version
```

**Describe alternatives you've considered**

From within a Dockerfile, you can copy directories across composite images, but I have not fully tested this and I don't have a universal/portable way to ensure shims are properly installed/updated when copying from one image/machine to another.

**Challenges anticipated:**

1. Shims won't get copied over with the virtual env directory - they'd probably need to be re-initialized/refreshed by an explicit pipx command.
2. There may be limitations in portability based on (1) the version of python and (2) the platform and version of the host OS.

I think even if we mandate same python version and same core OS platform, this could have very high value in making compatible docker images composable.

**Comment by uranusjr** [comment]
IMO this is out of scope of pipx. Recreating an app installation is much more than just copying the virtual environment, and pipx should not take on complexities introduced by this functionality, being entirely unrelated to anything else it does.

**Comment by aaronsteers** [comment]
@uranusjr - Thanks for your honest opinion. I totally respect that this isn't a problem to be solved unique by `pipx` (admittedly, it does cover a lot of ground re: venvs and python code portability), but at the same time I also still think `pipx` might be uniquely positioned to understand (and ultimately _solve_) the problem of wrapping portable installs. I'm happy to contribute here or elsewhere towards this goal if others can help me understand the challenges to overcome.

Do we know if there are other challenges we need to solve beyond what I've enumerated above? Or more specifically, if we (1) migrated the archived virtual env folder, (2) found a way to migrate (or reinstall) pipx-style shims, and (3) if we control for platform and python versioning (probably by disallowing them), would we have a workable solution? Or are there additional challenges to solve I'm not thinking of?

**Comment by uranusjr** [comment]
pipx keeps some metadata external to the virtual environment to track dependency information not covered by standard Python mechanisms, you’ll need to export those as well.

But a virtual environment is fundamentally not copiable; some features may seem to work, but many break in ways not expected by the user. So the idea is eventually a dead end unless you can fix how virtual environments work in those regards. It’s not to say it’s a bad idea, not at all. But virtual environments are simply not ready for it.

Some things known to break, from the top of my head:

1. Entry points hard-code the virtual environment’s path, and when moved to another location will not be able to be executed.
2. The `python` commands in a virtual environment is generally a symlink or “redirector”, and will not work correctly if the target location does not have a Python installation in the exact same location as the one that created the virtual environment.
3. In some edge cases of the above situation, a `pip` command running in the virtual environment context will incorrectly install things to a global Python installation.

There’s [a very very long thread](https://discuss.python.org/t/5378) a while ago that went into details why virtual environments don’t work in various scenarios and how we can fix them, but ultimately there’s very little interest from Python Core Devs because, well, why do you want to move a virtual environment in the first place? Why not just `pip freeze` things inside it and provision a new one from scratch? Personally I don’t entirely buy that argument, but you’ll need to come up with a good reason to argue with that mindset (and you’ll need to bring the argument to the core devs, not here).

**Comment by aaronsteers** [comment]
@uranusjr - Sorry for not replying earlier to the above. This is giving me lots to think about and research, and I appreciate your time to explain and give the additional background.

I recently stumbled on [zipapp](https://docs.python.org/3/library/zipapp.html) in the standard library, which then led me to [pex](https://github.com/pantsbuild/pex) and [pipenv-pex](https://github.com/it-is-wednesday/pipenv-pex).

On reading more about pex, it seems we might be able to pex-ify existing virtual environments created by `pipx`. I'm curious if you are familiar with these tools and have any thoughts on how they might relate (or not relate) to something similar here with pipx. Do you have any thoughts on how/if this could be integrated with pipx?

Caveat:

I'm aware we are still somewhat OS and interpreter bound, and they would likely not work on a very different OS or Python intepreter but for my use case (dockerization), I don't see that as a problem though when I'm thinking of cloud deployments (my primary use case), since we can instantly spin up something derived based on a stable version like `docker run python:3.8`, which should always be stable with any virtual environments created out of that image.

**Comment by uranusjr** [comment]
I don’t have much experience to pex, but zipapp is a very established mechanism that is known to work (pip internally uses it as well). [Shiv](https://github.com/linkedin/shiv) is a similar tool built on zipapp.

There are some gochas to zipapp if a module is poorly implemented. Those issues are fortunately increasingly rare, and you can always patch them when necessary (since the zipapp veondors all the libraries by definition anyway). I would highly encourage you trying it out.

**Comment by aaronsteers** [comment]
Thanks, @uranusjr! I'll check it out! 😄

**Comment by gaborbernat** [comment]
> IMO this is out of scope of pipx. Recreating an app installation is much more than just copying the virtual environment, and pipx should not take on complexities introduced by this functionality, being entirely unrelated to anything else it does.
