### ISSUE TITLE
Pip args do not behave similarly for `pipx install` and `pipx run`

### ISSUE THREAD

**Issue by ypicard** [pypa/pipx#941]
**Describe the bug**
When installing a package with `pipx install`, which requires packages from both the public registry and a private one, it works:
`pipx install <package> --pip-args="--index-url=<private_url> --extra-index-url https://pypi.python.org/simple"`

When trying to run the same package using `pipx run`, it does not:
`pipx run <package> --pip-args="--index-url=<private_url> --extra-index-url https://pypi.python.org/simple"`

Result:
```bash
Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement <private_package> (from versions: none)
    ERROR: No matching distribution found for <private_package>
Error installing <package> from spec '<local_wheel>'.
```

Should i supply arguments in a different way here?

**Comment by meowmeowmeowcat** [comment]
Does `pipx run --pip-args="--index-url=<private_url> --extra-index-url https://pypi.python.org/simple" <package>` work for you?

**Comment by ypicard** [comment]
Yes, it does. Interesting, thank you.

I notice the `pipx upgrade-all` command does not take any `--pip-args` option, which means it is not possible to upgrade packages from private repositories this way? Can you confirm?

**Comment by meowmeowmeowcat** [comment]
No, `pipx upgrade-all` will reuse pip arguments passed in `pipx install`, so it should be able to upgrade packages from private repositories.

**Comment by NeffIsBack** [comment]
Hey i am trying to install a package from a private gitea repository with ssh. What would be the corresponding command (if even possible)?

I tried:
`pipx install <package> --pip-args='--index.url="git+ssh://<private-url>/package.git"'`

But i always get the error:
`WARNING: Cannot look at git URL git+ssh://<private-url>/package.git/<package> because it does not support lookup as web pages`

At [stackoverflow](https://stackoverflow.com/questions/64564188/how-to-install-python-package-namespace-from-private-bitbucket-git-repository) someone seems to got it working but i just can not get the syntax correct

**Comment by NeffIsBack** [comment]
Update:
After a lot of try and error i finally got it working. Maybe you would want to add this to "examples" in your documentation:
`pipx install git+ssh://<username>@<private-repo-domain>/<path-to>/<package.git>`

**Comment by meowmeowmeowcat** [comment]
> Also the pipx examples page does not look up-to-date (or correct). Atleast pip-args '--index-url=... throws an error as it must be pip-args='--index-url=...

Thanks for the heads up!
